# Generated by Django 5.1.2 on 2024-10-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_api', '0002_rename_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='age',
            field=models.CharField(default=18, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='postcode',
            field=models.CharField(max_length=25),
        ),
    ]
