# Generated by Django 5.1.2 on 2024-10-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_api', '0003_userinformation_age_alter_location_postcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='user',
            new_name='user_profile',
        ),
    ]
